import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { Modal, Button, Container, Form } from 'react-bootstrap';
import Icon from '@mdi/react';
import { mdiClose } from '@mdi/js';
const Modal02 = ({ show, onHide, title = '공지사항 작성' }) => {
    const [windowWidth, setWindowWidth] = useState(window.innerWidth);
    const isAccordionView = windowWidth < 768;
    return (_jsxs(Modal, { show: show, onHide: onHide, centered: true, dialogClassName: `modal584-dialog ${windowWidth < 768 ? 'mobile-view' : ''}`, contentClassName: "modal584-content", className: "modal584-wrapper", children: [_jsxs(Modal.Header, { className: "custom-modal-header d-flex align-items-center", children: [_jsx("h5", { className: "mb-0 custom-modal-title", children: title }), _jsx(Button, { variant: "link", className: "ms-auto p-0 border-0", onClick: onHide, "aria-label": "\uB2EB\uAE30", children: _jsx(Icon, { path: mdiClose, size: 1 }) })] }), _jsx(Modal.Body, { className: "modal584-body", children: _jsxs(Container, { fluid: true, style: { padding: 0 }, children: [_jsxs("div", { className: "modal584-line d-flex align-items-center mb-3", children: [_jsx("div", { className: "modal584-label", children: "\uC11C\uBE44\uC2A4\uAD6C\uBD84" }), _jsxs(Form.Select, { className: "modal584-select", children: [_jsx("option", { children: "\uAD6D\uD1A0\uC815\uBCF4\uD50C\uB7AB\uD3FC" }), _jsx("option", { children: "\uAD6D\uD1A0\uC815\uBCF4\uD50C\uB7AB\uD3FC" }), _jsx("option", { children: "\uAD6D\uD1A0\uC815\uBCF4\uD50C\uB7AB\uD3FC" })] })] }), _jsxs("div", { className: "modal584-line d-flex align-items-center mb-3", children: [_jsx("div", { className: "modal584-label", children: "\uB2F4\uB2F9\uBD80\uC11C" }), _jsxs(Form.Select, { className: "modal584-select", children: [_jsx("option", { children: "\uAD6D\uD1A0\uC870\uC0AC\uACFC" }), _jsx("option", { children: "\uD574\uC591\uD300" }), _jsx("option", { children: "\uD658\uACBD\uD300" })] })] }), _jsxs("div", { className: "modal584-line d-flex align-items-center mb-3", children: [_jsx("div", { className: "modal584-label", children: "\uC81C\uBAA9" }), _jsx(Form.Control, { type: "text", className: "modal584-input", placeholder: "\uC81C\uBAA9 \uC785\uB825" })] }), _jsxs("div", { className: "modal584-line d-flex align-items-start mb-3", children: [_jsx("div", { className: "modal584-label", style: { marginTop: '4px' }, children: "\uB0B4\uC6A9" }), _jsx(Form.Control, { as: "textarea", className: "modal584-textarea", rows: 4, placeholder: "\uB0B4\uC6A9 \uC785\uB825" })] }), _jsxs("div", { className: "modal584-line d-flex align-items-center mb-3", children: [_jsx("div", { className: "modal584-label", children: "\uCCA8\uBD80\uD30C\uC77C" }), _jsxs("div", { className: "custom-file-wrapper", style: { flex: 1, display: 'flex' }, children: [_jsx("input", { type: "text", className: "file-name-input", placeholder: "\uD30C\uC77C\uC744 \uC120\uD0DD\uD574\uC8FC\uC138\uC694", readOnly: true }), _jsx("label", { htmlFor: "fileInput", className: "file-select-btn", children: "\uD30C\uC77C \uC120\uD0DD" }), _jsx("input", { type: "file", id: "fileInput", style: { display: 'none' }, onChange: (e) => {
                                                const fileName = e.target.files?.[0]?.name || '';
                                                const input = document.querySelector('.file-name-input');
                                                if (input)
                                                    input.value = fileName;
                                            } })] })] })] }) }), _jsxs(Modal.Footer, { className: "modal584-footer d-flex justify-content-end", children: [_jsx(Button, { className: "list-btn", children: "\uBAA9\uB85D\uC73C\uB85C \uB3CC\uC544\uAC00\uAE30" }), _jsx(Button, { className: "save-btn", children: "\uC800\uC7A5" })] })] }));
};
export default Modal02;
